{"uuid": "0007c79d-31c8-4299-b5e2-f358146efc57", "children": ["ea752a17-dfff-4990-b255-d9e147221a7e"], "befores": [{"name": "create_new_user", "status": "passed", "start": 1734623080844, "stop": 1734623081353}], "afters": [{"name": "create_new_user::0", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='stellarburgers.nomoreparties.siteapi', port=443): Max retries exceeded with url: /auth/user (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000002652DDD6350>: Failed to resolve 'stellarburgers.nomoreparties.siteapi' ([Errno 11001] getaddrinfo failed)\"))\n", "trace": "  File \"C:\\Users\\mmavr\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mmavr\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\mmavr\\yandex\\Diplom\\Diplom_2\\confest.py\", line 18, in create_new_user\n    delete_user = requests.delete(MAIN_URL+DELETE, headers=generate_header_for_login(accessToken))\n  File \"C:\\Users\\mmavr\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 157, in delete\n    return request(\"delete\", url, **kwargs)\n  File \"C:\\Users\\mmavr\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mmavr\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\mmavr\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\mmavr\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1734623082821, "stop": 1734623093953}], "start": 1734623080844, "stop": 1734623093953}